import { pgTable, uuid, varchar, timestamp, text, numeric, integer } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';

export const parties = pgTable('parties', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  /** Legal / primary name (invoice name). */
  name: varchar('name', { length: 255 }).notNull(),
  /** Legacy single-role field kept in sync with is_customer / is_vendor. */
  kind: varchar('kind', { length: 20 }).notNull().default('customer'),
  code: varchar('code', { length: 40 }),
  phone: varchar('phone', { length: 30 }),
  email: varchar('email', { length: 320 }),
  address: varchar('address', { length: 500 }),
  taxId: varchar('tax_id', { length: 100 }),
  creditLimit: numeric('credit_limit', { precision: 18, scale: 2 }),
  paymentTermsDays: integer('payment_terms_days'),
  notes: text('notes'),

  displayName: varchar('display_name', { length: 255 }),
  legalName: varchar('legal_name', { length: 255 }),
  partyType: varchar('party_type', { length: 20 }).notNull().default('company'),
  isCustomer: varchar('is_customer', { length: 1 }).notNull().default('0'),
  isVendor: varchar('is_vendor', { length: 1 }).notNull().default('0'),
  nic: varchar('nic', { length: 30 }),
  brn: varchar('brn', { length: 50 }),
  tin: varchar('tin', { length: 50 }),
  vatNumber: varchar('vat_number', { length: 50 }),
  svatNumber: varchar('svat_number', { length: 50 }),
  taxStatus: varchar('tax_status', { length: 20 }).notNull().default('unknown'),
  phoneMobile: varchar('phone_mobile', { length: 30 }),
  phoneLandline: varchar('phone_landline', { length: 30 }),
  website: varchar('website', { length: 255 }),
  addressLine1: varchar('address_line1', { length: 255 }),
  addressLine2: varchar('address_line2', { length: 255 }),
  city: varchar('city', { length: 120 }),
  district: varchar('district', { length: 120 }),
  province: varchar('province', { length: 120 }),
  postalCode: varchar('postal_code', { length: 40 }),
  country: varchar('country', { length: 100 }).notNull().default('Sri Lanka'),
  contactPerson: varchar('contact_person', { length: 255 }),
  contactPhone: varchar('contact_phone', { length: 30 }),
  contactEmail: varchar('contact_email', { length: 320 }),
  preferredCurrency: varchar('preferred_currency', { length: 5 }).notNull().default('LKR'),
  bankName: varchar('bank_name', { length: 120 }),
  bankBranch: varchar('bank_branch', { length: 120 }),
  bankAccountName: varchar('bank_account_name', { length: 255 }),
  bankAccountNo: varchar('bank_account_no', { length: 80 }),
  bankSwift: varchar('bank_swift', { length: 30 }),
  status: varchar('status', { length: 20 }).notNull().default('active'),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});
