import {
  pgTable,
  uuid,
  varchar,
  timestamp,
  numeric,
  text,
  jsonb,
  integer,
  boolean,
} from 'drizzle-orm/pg-core';
import { tenants } from './tenants';
import { users } from './users';
import { transactions } from './transactions';
import { accounts } from './accounts';

/** Parent import profile (tenant-learned or system). */
export const bankStatementProfiles = pgTable('bank_statement_profiles', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').references(() => tenants.id),
  name: varchar('name', { length: 120 }).notNull(),
  bankHint: varchar('bank_hint', { length: 120 }),
  columnMap: jsonb('column_map').$type<Record<string, string | number>>().notNull().default({}),
  signConvention: varchar('sign_convention', { length: 40 }).notNull().default('signed_amount'),
  dateFormatHint: varchar('date_format_hint', { length: 40 }),
  skipRows: integer('skip_rows').notNull().default(0),
  sheetName: varchar('sheet_name', { length: 120 }),
  successCount: integer('success_count').notNull().default(0),
  version: integer('version').notNull().default(1),
  bankAccountId: uuid('bank_account_id').references(() => accounts.id),
  currentVersionId: uuid('current_version_id'),
  profileStatus: varchar('profile_status', { length: 20 }).default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

/** Versioned studio rules — never mutate approved versions in place. */
export const bankStatementProfileVersions = pgTable('bank_statement_profile_versions', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  profileId: uuid('profile_id').notNull().references(() => bankStatementProfiles.id),
  versionNumber: integer('version_number').notNull().default(1),
  status: varchar('status', { length: 20 }).notNull().default('draft'),
  columnMappings: jsonb('column_mappings').$type<Record<string, unknown>>().notNull().default({}),
  amountRules: jsonb('amount_rules').$type<Record<string, unknown>>().notNull().default({}),
  dateRules: jsonb('date_rules').$type<Record<string, unknown>>().notNull().default({}),
  rowFilters: jsonb('row_filters').$type<unknown[]>().notNull().default([]),
  structureFingerprint: jsonb('structure_fingerprint').$type<Record<string, unknown>>().notNull().default({}),
  sampleSignatures: jsonb('sample_signatures'),
  notes: text('notes'),
  createdBy: uuid('created_by').references(() => users.id),
  approvedBy: uuid('approved_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  supersededAt: timestamp('superseded_at', { withTimezone: true }),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankStatementImports = pgTable('bank_statement_imports', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  userId: uuid('user_id').notNull().references(() => users.id),
  period: varchar('period', { length: 7 }).notNull(),
  fileName: varchar('file_name', { length: 255 }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('open'),
  rowCount: numeric('row_count', { precision: 10, scale: 0 }).notNull().default('0'),
  matchedCount: numeric('matched_count', { precision: 10, scale: 0 }).notNull().default('0'),
  unmatchedCount: numeric('unmatched_count', { precision: 10, scale: 0 }).notNull().default('0'),
  metadata: jsonb('metadata'),
  bankAccountId: uuid('bank_account_id').references(() => accounts.id),
  bookDomain: varchar('book_domain', { length: 20 }),
  fileSha256: varchar('file_sha256', { length: 64 }),
  storageKey: varchar('storage_key', { length: 500 }),
  periodFrom: varchar('period_from', { length: 10 }),
  periodTo: varchar('period_to', { length: 10 }),
  parserProfileId: uuid('parser_profile_id').references(() => bankStatementProfiles.id),
  source: varchar('source', { length: 20 }).default('erp_recon'),
  /** Studio: open | draft | ready | committed | voided | rolled_back */
  wizardStatus: varchar('wizard_status', { length: 20 }).default('open'),
  wizardStep: varchar('wizard_step', { length: 40 }),
  draftPayload: jsonb('draft_payload'),
  draftVersion: integer('draft_version').notNull().default(1),
  contentFingerprint: varchar('content_fingerprint', { length: 64 }),
  openingBalance: numeric('opening_balance', { precision: 18, scale: 2 }),
  closingBalance: numeric('closing_balance', { precision: 18, scale: 2 }),
  totalMoneyIn: numeric('total_money_in', { precision: 18, scale: 2 }),
  totalMoneyOut: numeric('total_money_out', { precision: 18, scale: 2 }),
  idempotencyKey: varchar('idempotency_key', { length: 80 }),
  profileVersionId: uuid('profile_version_id').references(() => bankStatementProfileVersions.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankStatementLines = pgTable('bank_statement_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  importId: uuid('import_id').notNull().references(() => bankStatementImports.id),
  matchedTransactionId: uuid('matched_transaction_id').references(() => transactions.id),
  rowNumber: numeric('row_number', { precision: 10, scale: 0 }).notNull(),
  transactionDate: varchar('transaction_date', { length: 10 }).notNull(),
  description: varchar('description', { length: 1000 }).notNull(),
  amount: numeric('amount', { precision: 18, scale: 2 }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('review'),
  raw: jsonb('raw'),
  reviewedByUserId: uuid('reviewed_by_user_id').references(() => users.id),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  notes: text('notes'),
  fingerprint: varchar('fingerprint', { length: 64 }),
  direction: varchar('direction', { length: 10 }),
  balanceAfter: numeric('balance_after', { precision: 18, scale: 2 }),
  externalRef: varchar('external_ref', { length: 100 }),
  matchScore: numeric('match_score', { precision: 5, scale: 4 }),
  matchMethod: varchar('match_method', { length: 20 }),
  matchCandidates: jsonb('match_candidates'),
  proposedAction: varchar('proposed_action', { length: 20 }).default('review'),
  createdTransactionId: uuid('created_transaction_id').references(() => transactions.id),
  confidence: numeric('confidence', { precision: 5, scale: 4 }),
  valueDate: varchar('value_date', { length: 10 }),
  debitAmount: numeric('debit_amount', { precision: 18, scale: 2 }),
  creditAmount: numeric('credit_amount', { precision: 18, scale: 2 }),
  validationStatus: varchar('validation_status', { length: 20 }).default('valid'),
  validationMessages: jsonb('validation_messages'),
  sourceRowHash: varchar('source_row_hash', { length: 64 }),
  transformLog: jsonb('transform_log'),
  reconciliationStatus: varchar('reconciliation_status', { length: 20 }).default('unmatched'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankStatementImportEvents = pgTable('bank_statement_import_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  importId: uuid('import_id').notNull().references(() => bankStatementImports.id),
  userId: uuid('user_id').notNull().references(() => users.id),
  lineId: uuid('line_id').references(() => bankStatementLines.id),
  action: varchar('action', { length: 40 }).notNull(),
  detail: jsonb('detail'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const bankImportIssues = pgTable('bank_import_issues', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  importId: uuid('import_id').notNull().references(() => bankStatementImports.id),
  lineId: uuid('line_id').references(() => bankStatementLines.id),
  issueType: varchar('issue_type', { length: 40 }).notNull(),
  severity: varchar('severity', { length: 20 }).notNull().default('error'),
  status: varchar('status', { length: 20 }).notNull().default('open'),
  title: varchar('title', { length: 255 }).notNull(),
  detail: jsonb('detail'),
  resolution: varchar('resolution', { length: 40 }),
  resolutionDetail: jsonb('resolution_detail'),
  applyToSimilar: boolean('apply_to_similar').notNull().default(false),
  resolvedBy: uuid('resolved_by').references(() => users.id),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const periodLocks = pgTable('period_locks', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  userId: uuid('user_id').notNull().references(() => users.id),
  period: varchar('period', { length: 7 }).notNull(),
  status: varchar('status', { length: 20 }).notNull().default('locked'),
  lockedAt: timestamp('locked_at', { withTimezone: true }).defaultNow().notNull(),
  unlockedAt: timestamp('unlocked_at', { withTimezone: true }),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

/** Workbench: bank account + statement period (authoritative recon object). */
export const bankReconciliationSessions = pgTable('bank_reconciliation_sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  bankAccountId: uuid('bank_account_id').notNull().references(() => accounts.id),
  bookDomain: varchar('book_domain', { length: 20 }),
  periodFrom: varchar('period_from', { length: 10 }).notNull(),
  periodTo: varchar('period_to', { length: 10 }).notNull(),
  statementReference: varchar('statement_reference', { length: 120 }),
  status: varchar('status', { length: 30 }).notNull().default('ready'),
  statementOpeningBalance: numeric('statement_opening_balance', { precision: 18, scale: 2 }),
  statementClosingBalance: numeric('statement_closing_balance', { precision: 18, scale: 2 }),
  bookOpeningBalanceSnapshot: numeric('book_opening_balance_snapshot', { precision: 18, scale: 2 }),
  bookClosingBalanceSnapshot: numeric('book_closing_balance_snapshot', { precision: 18, scale: 2 }),
  outstandingNet: numeric('outstanding_net', { precision: 18, scale: 2 }).notNull().default('0'),
  adjustmentNet: numeric('adjustment_net', { precision: 18, scale: 2 }).notNull().default('0'),
  differenceAmount: numeric('difference_amount', { precision: 18, scale: 2 }).notNull().default('0'),
  toleranceAmount: numeric('tolerance_amount', { precision: 18, scale: 2 }).notNull().default('0.01'),
  sourceFileCount: integer('source_file_count').notNull().default(0),
  bankLineCount: integer('bank_line_count').notNull().default(0),
  resolvedCaseCount: integer('resolved_case_count').notNull().default(0),
  openCaseCount: integer('open_case_count').notNull().default(0),
  version: integer('version').notNull().default(1),
  preparedBy: uuid('prepared_by').references(() => users.id),
  reconciledBy: uuid('reconciled_by').references(() => users.id),
  reconciledAt: timestamp('reconciled_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankReconciliationSessionImports = pgTable('bank_reconciliation_session_imports', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  sessionId: uuid('session_id').notNull().references(() => bankReconciliationSessions.id),
  importId: uuid('import_id').notNull().references(() => bankStatementImports.id),
  attachedBy: uuid('attached_by').references(() => users.id),
  attachedAt: timestamp('attached_at', { withTimezone: true }).defaultNow().notNull(),
});

export const bankReconciliationCases = pgTable('bank_reconciliation_cases', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  sessionId: uuid('session_id').notNull().references(() => bankReconciliationSessions.id),
  caseType: varchar('case_type', { length: 40 }).notNull(),
  confidence: varchar('confidence', { length: 20 }).notNull().default('none'),
  state: varchar('state', { length: 30 }).notNull().default('suggested'),
  matchScore: numeric('match_score', { precision: 5, scale: 4 }),
  matchMethod: varchar('match_method', { length: 20 }),
  explanation: text('explanation'),
  reasonCodes: jsonb('reason_codes').$type<string[]>().notNull().default([]),
  userLabel: varchar('user_label', { length: 80 }),
  resultLabel: varchar('result_label', { length: 80 }),
  createdTransactionId: uuid('created_transaction_id').references(() => transactions.id),
  exclusionReason: varchar('exclusion_reason', { length: 80 }),
  deferredUntil: varchar('deferred_until', { length: 10 }),
  sortDate: varchar('sort_date', { length: 10 }),
  sortAmount: numeric('sort_amount', { precision: 18, scale: 2 }),
  version: integer('version').notNull().default(1),
  confirmedBy: uuid('confirmed_by').references(() => users.id),
  confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankReconciliationCaseBankLines = pgTable('bank_reconciliation_case_bank_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  caseId: uuid('case_id').notNull().references(() => bankReconciliationCases.id),
  bankLineId: uuid('bank_line_id').notNull().references(() => bankStatementLines.id),
  allocatedAmount: numeric('allocated_amount', { precision: 18, scale: 2 }),
  role: varchar('role', { length: 30 }).notNull().default('primary'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankReconciliationCaseBookTransactions = pgTable(
  'bank_reconciliation_case_book_transactions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
    caseId: uuid('case_id').notNull().references(() => bankReconciliationCases.id),
    transactionId: uuid('transaction_id').notNull().references(() => transactions.id),
    allocatedAmount: numeric('allocated_amount', { precision: 18, scale: 2 }),
    role: varchar('role', { length: 30 }).notNull().default('primary'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    voidedAt: timestamp('voided_at', { withTimezone: true }),
  },
);

export const bankReconciliationOutstandingItems = pgTable('bank_reconciliation_outstanding_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  sessionId: uuid('session_id').notNull().references(() => bankReconciliationSessions.id),
  transactionId: uuid('transaction_id').notNull().references(() => transactions.id),
  caseId: uuid('case_id').references(() => bankReconciliationCases.id),
  reason: varchar('reason', { length: 40 }).notNull().default('not_cleared'),
  expectedClearDate: varchar('expected_clear_date', { length: 10 }),
  status: varchar('status', { length: 20 }).notNull().default('open'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  voidedAt: timestamp('voided_at', { withTimezone: true }),
});

export const bankReconciliationEvents = pgTable('bank_reconciliation_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  sessionId: uuid('session_id').notNull().references(() => bankReconciliationSessions.id),
  caseId: uuid('case_id').references(() => bankReconciliationCases.id),
  userId: uuid('user_id').notNull().references(() => users.id),
  action: varchar('action', { length: 40 }).notNull(),
  beforeValues: jsonb('before_values'),
  afterValues: jsonb('after_values'),
  reason: text('reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const bankReconciliationSnapshots = pgTable('bank_reconciliation_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id),
  sessionId: uuid('session_id').notNull().references(() => bankReconciliationSessions.id),
  summary: jsonb('summary').$type<Record<string, unknown>>().notNull().default({}),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
